USE QLDT

--Q1
SELECT HOTEN,LUONG 
FROM GIAOVIEN
WHERE PHAI=N'Nữ'

--Q2
SELECT HOTEN,LUONG AS LUONG_TRUOC,LUONG*1.1 AS LUONG_SAU
FROM GIAOVIEN

--Q3
SELECT DISTINCT MAGV
FROM GIAOVIEN, BOMON 
WHERE HOTEN LIKE N'Nguyễn%' AND LUONG > 2000 OR (TRUONGBM = MAGV AND YEAR(NGAYNHANCHUC)>1995) 

--Q4
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA=N'Công nghệ thông tin'

--Q5
SELECT *
FROM BOMON LEFT JOIN GIAOVIEN ON TRUONGBM = MAGV

--Q6
SELECT *
FROM GIAOVIEN GV LEFT JOIN BOMON BM ON BM.MABM=GV.MABM

--Q7
SELECT TENDT, GIAOVIEN.*
FROM DETAI LEFT JOIN GIAOVIEN ON MAGV = GVCNDT

--Q8
SELECT *
FROM KHOA LEFT JOIN GIAOVIEN ON TRUONGKHOA = MAGV

--Q9
SELECT DISTINCT GV.*
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MADT='006' AND TG.MAGV=GV.MAGV
JOIN BOMON BM ON GV.MABM=BM.MABM 
WHERE BM.TENBM = N'Vi sinh' 

--Q10
SELECT MADT, CHUDE.* ,HOTEN, NGSINH, DIACHI
FROM DETAI,CHUDE,GIAOVIEN
WHERE CAPQL=N'Thành phố' AND DETAI.MACD=CHUDE.MACD AND DETAI.GVCNDT=GIAOVIEN.MAGV

--Q11
SELECT GV.HOTEN AS HOTEN_TUNG_GV, QLCM.* FROM GIAOVIEN GV LEFT JOIN GIAOVIEN QLCM
ON GV.GVQLCM = QLCM.MAGV

--Q12 
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN GIAOVIEN QLCM ON GV.GVQLCM = QLCM.MAGV
WHERE QLCM.HOTEN = N'Nguyễn Thanh Tùng'

--Q13
SELECT HOTEN
FROM GIAOVIEN JOIN BOMON ON MAGV=TRUONGBM 
WHERE TENBM=N'Hệ thống thông tin'

--Q14 
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV=DT.GVCNDT
JOIN CHUDE CD ON DT.MACD=CD.MACD 
WHERE CD.TENCD= N'Quản lý giáo dục'

--Q15
SELECT TENCV
FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT=DT.MADT 
WHERE DT.TENDT = N'HTTT quản lý các trường ĐH' 
AND DATEDIFF(M, CV.NGAYBD, '3/1/2008') = 0

--Q16
SELECT GV.HOTEN AS HOTEN_GV, QLCM.HOTEN AS HOTEN_QLCM
FROM GIAOVIEN GV JOIN GIAOVIEN QLCM ON GV.GVQLCM = QLCM.MAGV

--Q17
SELECT *
FROM CONGVIEC
WHERE NGAYBD BETWEEN '01/01/2007' AND '08/01/2007'

--Q18
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN GIAOVIEN TTH ON GV.MABM=TTH.MABM
WHERE TTH.HOTEN=N'Trần Trà Hương' AND GV.HOTEN<>TTH.HOTEN

--Q19
SELECT DISTINCT GIAOVIEN.*
FROM GIAOVIEN JOIN BOMON ON TRUONGBM = MAGV
JOIN DETAI ON GVCNDT = MAGV

--Q20
SELECT HOTEN
FROM GIAOVIEN JOIN BOMON ON MAGV = TRUONGBM 
JOIN KHOA ON MAGV = TRUONGKHOA

--Q21
SELECT DISTINCT HOTEN
FROM GIAOVIEN JOIN BOMON ON MAGV = TRUONGBM 
JOIN DETAI ON MAGV = GVCNDT

--Q22
SELECT DISTINCT MAGV
FROM GIAOVIEN JOIN KHOA ON MAGV = TRUONGKHOA
JOIN DETAI ON MAGV = GVCNDT

--Q23
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MABM='HTTT' OR (TG.MADT='001' AND TG.MAGV=GV.MAGV)

--Q24
SELECT GV.* 
FROM GIAOVIEN GV JOIN GIAOVIEN GV002 ON GV.MABM = GV002.MABM
WHERE GV002.MAGV='002' AND GV.MAGV<>GV002.MAGV

--Q25
SELECT GIAOVIEN.*
FROM GIAOVIEN JOIN BOMON ON MAGV=TRUONGBM

--Q26
SELECT HOTEN, LUONG
FROM GIAOVIEN 