USE QLCB

--Q1
SELECT DISTINCT NV.MANV, NV.TEN AS TEN_PHICONG, NV.DCHI, NV.DTHOAI
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV AND NV.LOAINV=1
JOIN LICHBAY LB ON LB.MACB=PC.MACB
WHERE LB.MALOAI='B747'

--Q2
SELECT LB.MACB,LB.NGAYDI 
FROM LICHBAY LB JOIN CHUYENBAY CB ON LB.MACB=CB.MACB
WHERE CB.SBDI='DCA' AND (CB.GIODI BETWEEN '14:00' AND '18:00')

--Q3
SELECT DISTINCT NV.TEN
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV
JOIN CHUYENBAY CB ON PC.MACB=CB.MACB
WHERE CB.SBDI='SLC' AND CB.MACB='100'

--Q4
SELECT DISTINCT LB.MALOAI, LB.SOHIEU
FROM LICHBAY LB JOIN CHUYENBAY CB ON LB.MACB=CB.MACB
WHERE CB.SBDI='MIA'

--Q5
SELECT DC.MACB, DC.NGAYDI, KH.TEN, KH.DCHI, KH.DTHOAI
FROM KHACHHANG KH JOIN DATCHO DC ON KH.MAKH=DC.MAKH
ORDER BY DC.MACB ASC, DC.NGAYDI DESC

--Q6
SELECT PC.MACB, PC.NGAYDI, NV.TEN, NV.DCHI, NV.DTHOAI
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV
ORDER BY PC.MACB ASC, PC.NGAYDI DESC

--Q7
SELECT CB.MACB, PC.NGAYDI, NV.MANV, NV.TEN AS TEN_PHICONG
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV AND NV.LOAINV=1
JOIN CHUYENBAY CB ON CB.MACB=PC.MACB
WHERE CB.SBDEN='ORD'

--Q8
SELECT PC.MACB, PC.NGAYDI, NV.TEN AS TEN_PHICONG
FROM PHANCONG PC JOIN NHANVIEN NV ON NV.MANV=PC.MANV 
WHERE NV.MANV='1001' AND NV.LOAINV=1

--Q9
SELECT CB.MACB, CB.SBDI, CB.GIODI, CB.GIODEN, LB.NGAYDI
FROM CHUYENBAY CB JOIN LICHBAY LB ON LB.MACB=CB.MACB
WHERE CB.SBDEN='DEN'
ORDER BY LB.NGAYDI DESC, CB.SBDI ASC

--Q10
SELECT NV.TEN AS TEN_PHICONG, LM.HANGSX, LM.MALOAI
FROM NHANVIEN NV JOIN KHANANG KN ON NV.MANV=KN.MANV AND NV.LOAINV=1
JOIN LOAIMB LM ON LM.MALOAI=KN.MALOAI

--Q11
SELECT NV.MANV, NV.TEN AS TEN_PHICONG
FROM PHANCONG PC JOIN NHANVIEN NV ON NV.MANV=PC.MANV AND NV.LOAINV=1
WHERE PC.MACB='100' AND DATEDIFF(D,PC.NGAYDI,'11/01/2000')=0

--Q12
SELECT CB.MACB, NV.MANV, NV.TEN 
FROM PHANCONG PC JOIN NHANVIEN NV ON NV.MANV=PC.MANV 
JOIN CHUYENBAY CB ON CB.MACB=PC.MACB
WHERE DATEDIFF(D,PC.NGAYDI,'10/31/2000')=0 AND CB.GIODI = '20:30' AND CB.SBDI='MIA'

--Q13
SELECT PC.MACB, LB.SOHIEU, LB.MALOAI, LM.HANGSX
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV AND NV.LOAINV=1 AND NV.TEN = N'Quang'
JOIN LICHBAY LB ON LB.MACB=PC.MACB AND DATEDIFF(D,PC.NGAYDI,LB.NGAYDI)=0
JOIN LOAIMB LM ON LB.MALOAI=LM.MALOAI

--Q14
SELECT DISTINCT TEN AS TEN_PHICONG_CHUA_PHANCONG
FROM NHANVIEN 
WHERE LOAINV=1 AND MANV NOT IN (SELECT MANV FROM PHANCONG)

--Q15
SELECT DISTINCT KH.TEN AS KH_DI_MB_BOEING
FROM KHACHHANG KH JOIN DATCHO DC ON KH.MAKH=DC.MAKH
JOIN LICHBAY LB ON LB.MACB=DC.MACB AND DATEDIFF(D,DC.NGAYDI,LB.NGAYDI)=0
JOIN LOAIMB LM ON LM.MALOAI=LB.MALOAI
WHERE LM.HANGSX='Boeing'

--Q16
SELECT DISTINCT MACB
FROM LICHBAY
WHERE SOHIEU='10' AND MALOAI='B747'
