USE QLDT

--35
SELECT DISTINCT LUONG AS LUONG_CAONHAT
FROM GIAOVIEN
WHERE LUONG>=ALL(SELECT (LUONG) FROM GIAOVIEN)

--36
SELECT *
FROM GIAOVIEN
WHERE LUONG>=ALL(SELECT (LUONG) FROM GIAOVIEN)

--37
SELECT DISTINCT LUONG AS HTTT_LUONG_CAONHAT FROM GIAOVIEN
WHERE LUONG>= ALL(SELECT (LUONG) FROM GIAOVIEN WHERE MABM='HTTT')

--38 
SELECT HOTEN
FROM GIAOVIEN GV1 JOIN BOMON BM ON GV1.MABM=BM.MABM 
WHERE BM.TENBM=N'Hệ thống thông tin' AND (YEAR(GV1.NGSINH))<=ALL(SELECT (YEAR(GV2.NGSINH)) FROM GIAOVIEN GV2
WHERE GV1.MABM=GV2.MABM)

--39
SELECT HOTEN
FROM GIAOVIEN GV1 JOIN BOMON BM1 ON GV1.MABM=BM1.MABM JOIN KHOA K1 ON BM1.MAKHOA=K1.MAKHOA
WHERE K1.TENKHOA=N'Công nghệ thông tin' AND (YEAR(GV1.NGSINH))>=ALL(SELECT (YEAR(GV2.NGSINH))
FROM GIAOVIEN GV2 JOIN BOMON BM2 ON GV2.MABM=BM2.MABM JOIN KHOA K2 ON BM2.MAKHOA=K2.MAKHOA 
WHERE K1.MAKHOA=K2.MAKHOA)

--40
SELECT HOTEN,TENKHOA
FROM KHOA K JOIN BOMON BM ON K.MAKHOA=BM.MAKHOA JOIN GIAOVIEN GV ON BM.MABM=GV.MABM
WHERE GV.LUONG>=ALL(SELECT LUONG FROM GIAOVIEN)

--41 
SELECT *
FROM GIAOVIEN GV1
WHERE GV1.LUONG>=ALL(SELECT GV2.LUONG FROM GIAOVIEN GV2 
WHERE GV1.MABM=GV2.MABM)

--42
SELECT TENDT
FROM DETAI
WHERE MADT NOT IN (SELECT MADT FROM THAMGIADT TG JOIN GIAOVIEN GV ON TG.MAGV=GV.MAGV
WHERE GV.HOTEN=N'Nguyễn Hoài An')

--43
SELECT DT.TENDT, CN.HOTEN AS GVCNDT
FROM DETAI DT JOIN GIAOVIEN CN ON DT.GVCNDT=CN.MAGV
WHERE DT.MADT NOT IN (SELECT MADT FROM THAMGIADT TG JOIN GIAOVIEN GV ON TG.MAGV=GV.MAGV
WHERE GV.HOTEN=N'Nguyễn Hoài An')

--44
SELECT HOTEN
FROM GIAOVIEN 
WHERE MAGV NOT IN (SELECT MAGV FROM THAMGIADT) 
AND MABM IN (SELECT MABM FROM BOMON JOIN KHOA ON BOMON.MAKHOA=KHOA.MAKHOA 
WHERE TENKHOA = N'Công nghệ thông tin')

--45
SELECT *
FROM GIAOVIEN
WHERE MAGV NOT IN (SELECT MAGV FROM THAMGIADT)

--46
SELECT *
FROM GIAOVIEN
WHERE LUONG > (SELECT (HA.LUONG) FROM GIAOVIEN HA 
WHERE HA.HOTEN = N'Nguyễn Hoài An')

--47
SELECT *
FROM GIAOVIEN 
WHERE MAGV IN (SELECT TRUONGBM FROM BOMON) AND MAGV IN (SELECT MAGV FROM THAMGIADT)

--48 
SELECT *
FROM GIAOVIEN GV1
WHERE EXISTS (SELECT * FROM GIAOVIEN GV2 
WHERE GV1.HOTEN LIKE GV2.HOTEN AND GV1.MABM=GV2.MABM AND GV1.PHAI=GV2.PHAI AND GV1.MAGV<>GV2.MAGV)

--49
SELECT *
FROM GIAOVIEN
WHERE LUONG > ANY (SELECT LUONG FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM=GV.MABM 
WHERE BM.TENBM = N'Công nghệ phần mềm')

--50
SELECT *
FROM GIAOVIEN
WHERE LUONG > ALL (SELECT (LUONG) FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM=GV.MABM 
WHERE BM.TENBM = N'Hệ thống thông tin')

--51
SELECT TENKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM=GV.MABM JOIN KHOA K ON BM.MAKHOA=K.MAKHOA
GROUP BY K.TENKHOA
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM=GV.MABM JOIN KHOA K ON BM.MAKHOA=K.MAKHOA
GROUP BY K.TENKHOA)

--52
SELECT HOTEN
FROM GIAOVIEN
WHERE MAGV IN (SELECT GVCNDT FROM DETAI
GROUP BY GVCNDT
HAVING COUNT(*)>=ALL(SELECT COUNT(*) FROM DETAI
GROUP BY GVCNDT))

--53
SELECT BM.MABM 
FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM=GV.MABM 
GROUP BY BM.MABM
HAVING COUNT(*) >= ALL(SELECT COUNT(*) 
FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM=GV.MABM 
GROUP BY BM.MABM)

--54 
SELECT HOTEN, TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM=GV.MABM
WHERE GV.MAGV IN (SELECT MAGV FROM THAMGIADT
GROUP BY MAGV
HAVING COUNT (DISTINCT MADT) >= ALL(SELECT COUNT (DISTINCT MADT)
FROM THAMGIADT 
GROUP BY MAGV))

--55 
SELECT HOTEN
FROM GIAOVIEN WHERE MABM= 'HTTT' AND MAGV IN (SELECT MAGV FROM THAMGIADT
GROUP BY MAGV
HAVING COUNT (DISTINCT MADT) >= ALL(SELECT COUNT (DISTINCT MADT)
FROM THAMGIADT 
WHERE GIAOVIEN.MAGV = THAMGIADT.MAGV
GROUP BY MAGV))

--56
SELECT HOTEN, TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM=GV.MABM
WHERE GV.MAGV IN (SELECT MAGV FROM NGUOITHAN
GROUP BY MAGV
HAVING COUNT(*)>=ALL(SELECT COUNT(*) FROM NGUOITHAN 
GROUP BY MAGV))

--57
SELECT HOTEN
FROM GIAOVIEN WHERE MAGV IN (SELECT TRUONGBM FROM BOMON)
AND MAGV IN (SELECT GVCNDT FROM DETAI
GROUP BY GVCNDT
HAVING COUNT(*)>=ALL(SELECT COUNT(*) FROM DETAI
GROUP BY GVCNDT))

