USE QLCB

--34
SELECT HANGSX, LM.MALOAI, SOHIEU
FROM LOAIMB LM JOIN LICHBAY LB ON LM.MALOAI=LB.MALOAI
GROUP BY HANGSX, LM.MALOAI, SOHIEU
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
FROM LOAIMB LM JOIN LICHBAY LB ON LM.MALOAI=LB.MALOAI
GROUP BY HANGSX, LM.MALOAI, SOHIEU)

--35 
SELECT TEN
FROM NHANVIEN WHERE MANV IN (SELECT MANV FROM PHANCONG
GROUP BY MANV
HAVING COUNT(*) >= ALL(SELECT COUNT(*) FROM PHANCONG
GROUP BY MANV))

--36
SELECT TEN, DCHI, DTHOAI
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV AND NV.LOAINV=1 
GROUP BY TEN, DCHI, DTHOAI
HAVING COUNT(*) >= ALL(SELECT COUNT(*) 
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV AND NV.LOAINV=1 
GROUP BY TEN, DCHI, DTHOAI)

--37
SELECT SBDEN, COUNT(*) AS SOLUONG_CB_HACANH
FROM CHUYENBAY  
GROUP BY SBDEN
HAVING COUNT(*) <= ALL(SELECT COUNT(*) FROM CHUYENBAY  
GROUP BY SBDEN)

--38
SELECT SBDI, COUNT(*) AS SOLUONG_CB_XUATPHAT
FROM CHUYENBAY  
GROUP BY SBDI
HAVING COUNT(*) >= ALL(SELECT COUNT(*) FROM CHUYENBAY  
GROUP BY SBDI)

--39
SELECT TEN, DCHI, DTHOAI
FROM DATCHO DC JOIN KHACHHANG KH ON DC.MAKH=KH.MAKH
GROUP BY TEN, DCHI, DTHOAI
HAVING COUNT(*) >= ALL(SELECT COUNT(*) 
FROM DATCHO DC JOIN KHACHHANG KH ON DC.MAKH=KH.MAKH
GROUP BY TEN, DCHI, DTHOAI)

--40
SELECT MANV, TEN, LUONG
FROM NHANVIEN 
WHERE MANV IN (SELECT MANV FROM KHANANG 
GROUP BY MANV
HAVING COUNT(*) >= ALL(SELECT COUNT(*) FROM KHANANG 
GROUP BY MANV))

--41
SELECT MANV, TEN, LUONG
FROM NHANVIEN
WHERE LUONG >= ALL(SELECT (LUONG) FROM NHANVIEN)

--42
SELECT TEN, DCHI, MACB, NGAYDI
FROM NHANVIEN NV1 JOIN PHANCONG PC1 ON NV1.MANV=PC1.MANV
WHERE NV1.LUONG=(SELECT MAX(LUONG) FROM NHANVIEN NV2 JOIN PHANCONG PC2 ON NV2.MANV=PC2.MANV
AND PC1.MACB=PC2.MACB AND PC1.NGAYDI=PC2.NGAYDI
GROUP BY PC2.MACB, PC2.NGAYDI)

--43
SELECT MACB, GIODI, GIODEN
FROM CHUYENBAY
WHERE GIODI <= ALL(SELECT GIODI FROM CHUYENBAY)

--44
SELECT MACB, DATEDIFF(MI,GIODI,GIODEN) AS TG_BAY_TINH_BANG_PHUT
FROM CHUYENBAY
WHERE DATEDIFF(MI,GIODI,GIODEN) >= ALL(SELECT DATEDIFF(MI,GIODI,GIODEN) FROM CHUYENBAY)

--45
SELECT MACB, DATEDIFF(MI,GIODI,GIODEN) AS  TG_BAY_TINH_BANG_PHUT
FROM CHUYENBAY
WHERE DATEDIFF(MI,GIODI,GIODEN) <= ALL(SELECT DATEDIFF(MI,GIODI,GIODEN) FROM CHUYENBAY)

--46
SELECT MACB, NGAYDI
FROM LICHBAY 
WHERE MACB IN (SELECT MACB FROM LICHBAY
WHERE MALOAI='B747'
GROUP BY MACB
HAVING COUNT(*) >= ALL(SELECT COUNT(*) FROM LICHBAY
WHERE MALOAI='B747' 
GROUP BY MACB))

--47
SELECT PC.MACB, PC.NGAYDI, COUNT(*) AS SOLUONG_NV
FROM PHANCONG PC WHERE EXISTS (SELECT COUNT(*) FROM DATCHO DC
WHERE PC.MACB=DC.MACB AND PC.NGAYDI=DC.NGAYDI
GROUP BY DC.MACB, DC.NGAYDI
HAVING COUNT(DC.MAKH)>3) 
GROUP BY PC.MACB, PC.NGAYDI

--48
SELECT LOAINV, COUNT(*) AS SOLUONG_NV
FROM NHANVIEN
GROUP BY LOAINV
HAVING SUM(LUONG)>600000

--49
SELECT DC.MACB, DC.NGAYDI, COUNT(*) AS SOLUONG_KH
FROM DATCHO DC WHERE EXISTS (SELECT COUNT(*) FROM PHANCONG PC
WHERE PC.MACB=DC.MACB AND PC.NGAYDI=DC.NGAYDI
GROUP BY PC.MACB, PC.NGAYDI
HAVING COUNT(PC.MANV)>3) 
GROUP BY DC.MACB, DC.NGAYDI

--50
SELECT MALOAI, COUNT(*) AS SOLUONG_CB
FROM LICHBAY WHERE MALOAI IN (SELECT MALOAI FROM MAYBAY
GROUP BY MALOAI
HAVING COUNT(*)>1)
GROUP BY MALOAI