
--58
SELECT HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT CD.MACD
FROM CHUDE CD
EXCEPT 
SELECT MACD 
FROM THAMGIADT TG JOIN DETAI DT ON TG.MADT=DT.MADT
WHERE TG.MAGV=GV.MAGV)

SELECT HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM CHUDE CD WHERE NOT EXISTS (SELECT * 
FROM THAMGIADT TG JOIN DETAI DT ON TG.MADT=DT.MADT
WHERE TG.MAGV=GV.MAGV AND DT.MACD=CD.MACD))

SELECT HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV=GV.MAGV
JOIN DETAI DT ON TG.MADT=DT.MADT
GROUP BY HOTEN
HAVING COUNT(DISTINCT MACD)=(SELECT COUNT(*) FROM CHUDE)

--59 
SELECT TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT GV.MAGV
FROM GIAOVIEN GV
WHERE MABM='HTTT'
EXCEPT 
SELECT MAGV 
FROM THAMGIADT TG
WHERE DT.MADT=TG.MADT)

SELECT TENDT
FROM DETAI KQ
WHERE NOT EXISTS (SELECT *
FROM GIAOVIEN GV
WHERE MABM='HTTT' AND NOT EXISTS(SELECT *
FROM THAMGIADT TG
WHERE KQ.MADT=TG.MADT AND TG.MAGV=GV.MAGV))

SELECT TENDT
FROM THAMGIADT TG JOIN DETAI DT ON DT.MADT=TG.MADT
JOIN GIAOVIEN GV ON TG.MAGV=GV.MAGV
WHERE GV.MABM='HTTT' 
GROUP BY TENDT
HAVING COUNT(DISTINCT GV.MAGV)>=ALL(SELECT COUNT(*) 
FROM GIAOVIEN GV
WHERE MABM='HTTT')

--60
SELECT TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT GV.MAGV
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM
WHERE TENBM=N'Hệ thống thông tin'
EXCEPT 
SELECT MAGV 
FROM THAMGIADT TG
WHERE DT.MADT=TG.MADT)

SELECT TENDT
FROM DETAI KQ
WHERE NOT EXISTS (SELECT *
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM
WHERE TENBM=N'Hệ thống thông tin' AND NOT EXISTS(SELECT *
FROM THAMGIADT TG
WHERE KQ.MADT=TG.MADT AND TG.MAGV=GV.MAGV))

SELECT TENDT
FROM THAMGIADT TG JOIN DETAI DT ON DT.MADT=TG.MADT
JOIN GIAOVIEN GV ON TG.MAGV=GV.MAGV
JOIN BOMON BM ON GV.MABM=BM.MABM  
WHERE TENBM=N'Hệ thống thông tin'
GROUP BY TENDT
HAVING COUNT(DISTINCT GV.MAGV)>=ALL(SELECT COUNT(*) 
FROM GIAOVIEN GV
WHERE MABM='HTTT')

--61
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT DT.MADT
FROM DETAI DT
WHERE MACD='QLGD'
EXCEPT 
SELECT TG.MADT 
FROM THAMGIADT TG 
WHERE TG.MAGV=GV.MAGV)

SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM DETAI DT
WHERE MACD='QLGD' AND NOT EXISTS (SELECT * 
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV AND DT.MADT=TG.MADT))

SELECT GV.*
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV=GV.MAGV
JOIN DETAI DT ON TG.MADT=DT.MADT WHERE MACD='QLGD' 
GROUP BY GV.MAGV, GV.HOTEN, GV.PHAI, GV.NGSINH, GV.DIACHI, GV.GVQLCM, GV.LUONG, GV.MABM
HAVING COUNT(DISTINCT DT.TENDT)=(SELECT COUNT(*) FROM DETAI WHERE MACD='QLGD')

--62
SELECT HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT TG.MADT
FROM THAMGIADT TG JOIN GIAOVIEN TTH ON TG.MAGV=TTH.MAGV
WHERE TTH.HOTEN=N'Trần Trà Hương'
EXCEPT 
SELECT TG.MADT 
FROM THAMGIADT TG JOIN GIAOVIEN GV2 ON TG.MAGV=GV2.MAGV
WHERE GV2.HOTEN NOT LIKE N'Trần Trà Hương' AND TG.MAGV=GV.MAGV)


SELECT HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM THAMGIADT TG JOIN GIAOVIEN TTH ON TG.MAGV=TTH.MAGV
WHERE TTH.HOTEN=N'Trần Trà Hương' AND NOT EXISTS (SELECT * 
FROM THAMGIADT TG2
WHERE GV.HOTEN NOT LIKE N'Trần Trà Hương' AND TG2.MAGV=GV.MAGV AND TG2.MADT=TG.MADT))

SELECT HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV=GV.MAGV
WHERE GV.HOTEN NOT LIKE N'Trần Trà Hương' 
AND TG.MADT IN (SELECT MADT FROM THAMGIADT TG2 JOIN GIAOVIEN GV2 ON TG2.MAGV=GV2.MAGV
WHERE GV2.HOTEN=N'Trần Trà Hương')
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TG.MADT)=(SELECT COUNT(*) FROM THAMGIADT TG JOIN GIAOVIEN TTH ON TG.MAGV=TTH.MAGV WHERE TTH.HOTEN = N'Trần Trà Hương')


--63
--EXCEPT
SELECT TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT GV.MAGV
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM
WHERE TENBM=N'Hóa Hữu Cơ'
EXCEPT 
SELECT TG.MAGV 
FROM THAMGIADT TG
WHERE DT.MADT=TG.MADT)
--NOT EXISTS
SELECT TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM
WHERE TENBM=N'Hóa Hữu Cơ' AND NOT EXISTS (SELECT *
FROM THAMGIADT TG
WHERE DT.MADT=TG.MADT AND TG.MAGV=GV.MAGV))
--COUNT
SELECT TENDT
FROM THAMGIADT TG JOIN DETAI DT ON DT.MADT=TG.MADT
JOIN GIAOVIEN GV ON TG.MAGV=GV.MAGV
JOIN BOMON BM ON GV.MABM=BM.MABM  
WHERE TENBM=N'Hóa Hữu Cơ'
GROUP BY TENDT
HAVING COUNT(DISTINCT TG.MAGV)=(SELECT COUNT(*) FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM  
WHERE TENBM=N'Hóa Hữu Cơ')

--64
--EXCEPT
SELECT HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT CV.MADT, CV.SOTT
FROM CONGVIEC CV
WHERE CV.MADT='006'
EXCEPT 
SELECT TG.MADT, TG.STT
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV)
--NOT EXISTS
SELECT HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT *
FROM CONGVIEC CV
WHERE CV.MADT='006' AND NOT EXISTS (SELECT *
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV AND CV.MADT=TG.MADT AND CV.SOTT=TG.STT))
--COUNT
SELECT HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV=TG.MAGV
WHERE TG.MADT='006'
GROUP BY HOTEN
HAVING COUNT(DISTINCT TG.STT)=(SELECT COUNT(DISTINCT SOTT) FROM CONGVIEC WHERE MADT='006')

--65
--EXCEPT
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT DT.MADT
FROM DETAI DT JOIN CHUDE CD ON DT.MACD=CD.MACD
WHERE TENCD=N'Ứng dụng công nghệ'
EXCEPT 
SELECT TG.MADT 
FROM THAMGIADT TG 
WHERE TG.MAGV=GV.MAGV)
--NOT EXISTS
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM DETAI DT JOIN CHUDE CD ON DT.MACD=CD.MACD
WHERE TENCD=N'Ứng dụng công nghệ' AND NOT EXISTS (SELECT * 
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV AND DT.MADT=TG.MADT))
--COUNT
SELECT GV.*
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV=GV.MAGV
JOIN DETAI DT ON TG.MADT=DT.MADT  
JOIN CHUDE CD ON DT.MACD=CD.MACD
WHERE TENCD=N'Ứng dụng công nghệ' 
GROUP BY GV.MAGV, GV.HOTEN, GV.PHAI, GV.NGSINH, GV.DIACHI, GV.GVQLCM, GV.LUONG, GV.MABM
HAVING COUNT(DISTINCT DT.MADT)=(SELECT COUNT(*) FROM DETAI DT JOIN CHUDE CD ON DT.MACD=CD.MACD
WHERE TENCD=N'Ứng dụng công nghệ')

--66
--EXCEPT
SELECT HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS(
SELECT DT.MADT
FROM DETAI DT JOIN GIAOVIEN CN ON CN.MAGV=DT.GVCNDT
WHERE CN.HOTEN=N'Trần Trà Hương'
EXCEPT 
SELECT TG.MADT 
FROM THAMGIADT TG 
WHERE TG.MAGV=GV.MAGV)
--NOT EXISTS
SELECT HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM DETAI DT JOIN GIAOVIEN CN ON CN.MAGV=DT.GVCNDT
WHERE CN.HOTEN=N'Trần Trà Hương' AND NOT EXISTS (SELECT *
FROM THAMGIADT TG 
WHERE TG.MAGV=GV.MAGV AND DT.MADT=TG.MADT))
--COUNT
SELECT HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV=GV.MAGV
WHERE GV.HOTEN NOT LIKE N'Trần Trà Hương' 
AND TG.MADT IN (SELECT MADT FROM DETAI DT1 JOIN GIAOVIEN CN1 ON CN1.MAGV=DT1.GVCNDT
WHERE CN1.HOTEN=N'Trần Trà Hương')
GROUP BY GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT)=(SELECT COUNT(*) FROM DETAI DT JOIN GIAOVIEN CN ON CN.MAGV=DT.GVCNDT
WHERE CN.HOTEN=N'Trần Trà Hương')

--67
--EXCEPT
SELECT TENDT
FROM DETAI DT 
WHERE NOT EXISTS (
SELECT GV.MAGV
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM 
WHERE MAKHOA='CNTT'
EXCEPT 
SELECT TG.MAGV
FROM THAMGIADT TG
WHERE DT.MADT=TG.MADT)
--NOT EXISTS
SELECT TENDT
FROM DETAI DT 
WHERE NOT EXISTS (SELECT *
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM 
WHERE MAKHOA='CNTT' AND NOT EXISTS (SELECT *
FROM THAMGIADT TG
WHERE DT.MADT=TG.MADT AND TG.MAGV=GV.MAGV))
--COUNT
SELECT TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT=TG.MADT
JOIN GIAOVIEN GV ON TG.MAGV=GV.MAGV
JOIN BOMON BM ON GV.MABM=BM.MABM 
WHERE MAKHOA='CNTT'
GROUP BY TENDT
HAVING COUNT(DISTINCT GV.MAGV)=(SELECT COUNT(*) FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM 
WHERE MAKHOA='CNTT')

--68
--EXCEPT
SELECT HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (
SELECT CV.MADT, CV.SOTT
FROM CONGVIEC CV JOIN DETAI DT ON DT.MADT=CV.MADT
WHERE TENDT=N'Nghiên cứu tế bào gốc'
EXCEPT 
SELECT TG.MADT, TG.STT
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV)
--NOT EXISTS
SELECT HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT *
FROM CONGVIEC CV JOIN DETAI DT ON DT.MADT=CV.MADT
WHERE TENDT=N'Nghiên cứu tế bào gốc' AND NOT EXISTS (SELECT *
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV AND CV.MADT=TG.MADT AND CV.SOTT=TG.STT))
--COUNT
SELECT HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV=TG.MAGV
JOIN DETAI DT ON DT.MADT=TG.MADT
WHERE TENDT=N'Nghiên cứu tế bào gốc'
GROUP BY HOTEN
HAVING COUNT(DISTINCT TG.STT)=(SELECT COUNT(DISTINCT CV.SOTT) FROM CONGVIEC CV JOIN DETAI DT ON DT.MADT=CV.MADT
WHERE TENDT=N'Nghiên cứu tế bào gốc')

--69
--EXCEPT
SELECT HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
SELECT DT.MADT
FROM DETAI DT
WHERE KINHPHI>100
EXCEPT
SELECT TG.MADT
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV)
--NOT EXISTS
SELECT HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM DETAI DT
WHERE KINHPHI>100 AND NOT EXISTS (SELECT *
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV AND DT.MADT=TG.MADT))
--COUNT
SELECT HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV=TG.MAGV
JOIN DETAI DT ON DT.MADT=TG.MADT
WHERE KINHPHI>100
GROUP BY HOTEN
HAVING COUNT(DISTINCT TG.MADT)=(SELECT COUNT(*) FROM DETAI WHERE KINHPHI>100)

--70
--EXCEPT
SELECT TENDT
FROM DETAI DT 
WHERE NOT EXISTS (
SELECT GV.MAGV
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM JOIN KHOA K ON K.MAKHOA=BM.MAKHOA
WHERE TENKHOA=N'Sinh học'
EXCEPT 
SELECT TG.MAGV
FROM THAMGIADT TG
WHERE DT.MADT=TG.MADT)
--NOT EXISTS
SELECT TENDT
FROM DETAI DT 
WHERE NOT EXISTS (SELECT *
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM JOIN KHOA K ON K.MAKHOA=BM.MAKHOA
WHERE TENKHOA=N'Sinh học' AND NOT EXISTS (SELECT *
FROM THAMGIADT TG
WHERE DT.MADT=TG.MADT AND TG.MAGV=GV.MAGV))
--COUNT
SELECT TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT=TG.MADT
JOIN GIAOVIEN GV ON TG.MAGV=GV.MAGV
JOIN BOMON BM ON GV.MABM=BM.MABM 
JOIN KHOA K ON K.MAKHOA=BM.MAKHOA
WHERE TENKHOA=N'Sinh học'
GROUP BY TENDT
HAVING COUNT(DISTINCT GV.MAGV)=(SELECT COUNT(*) FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM JOIN KHOA K ON K.MAKHOA=BM.MAKHOA
WHERE TENKHOA=N'Sinh học')

--71
--EXCEPT
SELECT MAGV, HOTEN, NGSINH
FROM GIAOVIEN GV 
WHERE NOT EXISTS (
SELECT CV.MADT, CV.SOTT
FROM CONGVIEC CV JOIN DETAI DT ON DT.MADT=CV.MADT
WHERE TENDT=N'Ứng dụng hoá học xanh'
EXCEPT 
SELECT TG.MADT, TG.STT
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV)
--NOT EXISTS
SELECT MAGV, HOTEN, NGSINH
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT *
FROM CONGVIEC CV JOIN DETAI DT ON DT.MADT=CV.MADT
WHERE TENDT=N'Ứng dụng hoá học xanh' AND NOT EXISTS (SELECT *
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV AND CV.MADT=TG.MADT AND CV.SOTT=TG.STT))
--COUNT
SELECT GV.MAGV, HOTEN, NGSINH
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV=TG.MAGV
JOIN DETAI DT ON DT.MADT=TG.MADT
WHERE TENDT=N'Ứng dụng hoá học xanh'
GROUP BY GV.MAGV, HOTEN, NGSINH
HAVING COUNT(DISTINCT TG.STT)=(SELECT COUNT(DISTINCT CV.SOTT) FROM CONGVIEC CV JOIN DETAI DT ON DT.MADT=CV.MADT
WHERE TENDT=N'Ứng dụng hoá học xanh')

--72
--EXCEPT
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, QLCM.HOTEN AS TEN_QLCM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM
JOIN GIAOVIEN QLCM ON QLCM.MAGV=GV.GVQLCM
WHERE NOT EXISTS (SELECT DT.MADT
FROM DETAI DT JOIN CHUDE CD ON DT.MACD=CD.MACD
WHERE TENCD=N'Nghiên cứu phát triển'
EXCEPT 
SELECT TG.MADT 
FROM THAMGIADT TG 
WHERE TG.MAGV=GV.MAGV)
--NOT EXISTS
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, QLCM.HOTEN AS TEN_QLCM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM
JOIN GIAOVIEN QLCM ON QLCM.MAGV=GV.GVQLCM
WHERE NOT EXISTS (SELECT *
FROM DETAI DT JOIN CHUDE CD ON DT.MACD=CD.MACD
WHERE TENCD=N'Nghiên cứu phát triển' AND NOT EXISTS (SELECT * 
FROM THAMGIADT TG
WHERE TG.MAGV=GV.MAGV AND DT.MADT=TG.MADT))
--COUNT
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, QLCM.HOTEN AS TEN_QLCM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM=BM.MABM
JOIN GIAOVIEN QLCM ON QLCM.MAGV=GV.GVQLCM
JOIN THAMGIADT TG ON TG.MAGV=GV.MAGV
JOIN DETAI DT ON TG.MADT=DT.MADT  
JOIN CHUDE CD ON DT.MACD=CD.MACD
WHERE TENCD=N'Nghiên cứu phát triển' 
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM, QLCM.HOTEN
HAVING COUNT(DISTINCT DT.MADT)=(SELECT COUNT(*) FROM DETAI DT JOIN CHUDE CD ON DT.MACD=CD.MACD
WHERE TENCD=N'Nghiên cứu phát triển')


